//auth action type
export const SUCCESS_SIGN_UP = 'SUCCESS_SIGN_UP';
export const SUCCESS_LOGIN = 'SUCCESS_LOGIN';
export const SUCCESS_LOGOUT = 'SUCCESS_LOGOUT';
export const SET_USER = 'SET_USER'

//News Action 
export const ADD_TOP_HEADING_NEWS_LIST = 'ADD_TOP_HEADING_NEWS_LIST'
export const ADD_ALL_NEWS_LIST = 'ADD_ALL_NEWS_LIST'
export const ADD_RECOMMENDED_NEWS_LIST = 'ADD_RECOMMENDED_NEWS_LIST'

export const ADD_NEWS_POST_LIST = 'ADD_NEWS_POST_LIST'
export const ADD_NEWS_POST_TO_LIST = 'ADD_NEWS_POST_TO_LIST'

export const ADD_LIKED_NEWS_LIST = 'ADD_LIKED_NEWS_LIST'
export const ADD_LIKED_NEWS_TO_LIST = 'ADD_LIKED_NEWS_TO_LIST'

export const ADD_BOOKMARK_NEWS_LIST = 'ADD_BOOKMARK_NEWS_LIST'
export const ADD_BOOKMARK_NEWS_TO_LIST = 'ADD_BOOKMARK_NEWS_TO_LIST'
